[feature/12] Add lessons query
code4romania/teacher-workout-backend pull request #45
Opened 2021-07-31 13:52 UTC by pirvudoru

### What does it fix?

Closes #XXX 

### How has it been tested?

2021-07-31 14:14 UTC, RaduBuciuceanu requested changes
![image](https://user-images.githubusercontent.com/39530866/127742564-b0e06d1d-f878-4c37-b8b0-8c02fd155234.png)
Should we also remove those folder from inside the csproj file?

2021-07-31 14:14 UTC, RaduBuciuceanu commented on TeacherWorkout.Domain/Lessons/GetLessons.cs
> +            }
Won't it be cleaner to have a complex graph type together with a complex model used to filter lessons? By following this approach we can also add more filters without modifying the query contract.

2021-07-31 14:14 UTC, RaduBuciuceanu requested changes
Should we also remove the Api/WeatherForecast file?

2021-07-31 14:16 UTC, RaduBuciuceanu requested changes
As far as we are using feature folders for commands, should we also move the models into their related feature folder?

![image](https://user-images.githubusercontent.com/39530866/127742664-fbdd994d-82f2-48b2-88a5-afc9159f0b28.png)

2021-08-26 14:01 UTC, pirvudoru commented on TeacherWorkout.Domain/Lessons/GetLessons.cs
> +            }
Ended up doing that :+1:

2021-08-27 12:00 UTC, catileptic approved these changes

2021-08-27 12:00 UTC, merged