Feature/57 get and clean images
code4romania/teacher-workout-backend pull request #84
Opened 2023-12-02 15:20 UTC by nicolaes

### What does it fix?

Closes #57 : additional suggestions
This includes PR #83.

### How has it been tested?

TBD

2023-12-04 12:38 UTC, danielferecatu commented on TeacherWorkout.Api/GraphQL/TeacherWorkoutMutation.cs
> +                    if (file.Length > 5 * 1024 * 1024)
It's better for such values to keep them in config files. I don't know how to access the config from the mutation file, but maybe it's a topic for a new issue to open.

2023-12-04 13:59 UTC, nicolaes commented on TeacherWorkout.Api/GraphQL/TeacherWorkoutMutation.cs
> +                    if (file.Length > 5 * 1024 * 1024)
Thanks for the suggestion. Fixed - is this ok?

2023-12-04 14:42 UTC, danielferecatu commented on TeacherWorkout.Api/GraphQL/TeacherWorkoutMutation.cs
> +                    if (file.Length > 5 * 1024 * 1024)
Oh, I didn't know `TeacherWorkoutMutation` supports DI from service collection. It's more than perfect 😄

2023-12-04 14:42 UTC, danielferecatu approved these changes

2023-12-07 12:30 UTC, idormenco approved these changes

2023-12-07 12:30 UTC, idormenco commented on TeacherWorkout.Domain/Themes/CreateTheme.cs
> +        private readonly IFileBlobRepository _ifileBlobRepository = fileBlobRepository;
a better name will be `_fileBlobRepository`

2023-12-08 07:06 UTC, idormenco approved these changes
LGTM

2023-12-08 07:29 UTC, idormenco requested changes

2023-12-08 07:29 UTC, idormenco commented on TeacherWorkout.Api/Jobs/DeleteOldFileBlobsJob.cs
> +using DeUrgenta.RecurringJobs.Jobs.Config;
replace with `using TeacherWorkout.Api.Jobs.Config;`

2023-12-08 07:33 UTC, idormenco approved these changes

2023-12-08 12:23 UTC, merged